apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-anti-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fitness-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: fitness-container
        image: pulkit197/fitness_tracker-master-copy3-fitness-app:latest
        ports:
        - containerPort: 5000